# Archivo de configuración de dotsync
# Dotsync excluirá los patrones de nombres de archivos descritos en el array conf_exclude automáticamente
# al mover directorios al repositorio, recomendado poner archivos de logs, caché...

declare -a conf_exclude=(
	"*/nvim/lazy-lock.json"
	"*/nvim/*/plugins"
	"node_modules"
	".git"
	"*_history"
	"__pycache__"
    ".venv"
    "*.pyc"
)