# Archivo de configuración de dotsync
# Dotsync excluirá los patrones de nombres de archivos descritos en el array conf_exclude automáticamente
# al mover directorios al repositorio, recomendado poner archivos de logs, caché...
# Los patrones serán contrastados con la ruta completa del archivo o directorio
# Se recomienda el uso de comodines o definir rutas completas, se pueden usar variables como $HOME

declare -a conf_exclude=(
	"*/nvim/lazy-lock.json"
	"*/nvim/*/plugins/*"
	"*/node_modules/*"
	"*/.git*"
	"*history"
	"*/__pycache__/*"
    "*/.venv/*"
    "*.pyc"
)