# Para más información en cómo configurar este archivo, consulta la página de manual dotsync-conf(1)

declare -a conf_exclude=(
	"*cache*" 
	"*.log" 
	"*/logs/*" 
	"*/tmp/*" 
	"*/nvim/lazy-lock.json"
	"*/nvim/*/plugins/*"
	"*/node_modules/*"
	"*/.git*"
	"*history"
	"*/__pycache__/*"
    "*.pyc"
    "*/.venv/*"
)

auto_sync=true
