#!/usr/bin/env bash

load_config() {
    if ! [ -f "$CONF" ]; then
        return 0 # No pasa nada si el archivo de configuración no existe
    fi
    if ! source "$CONF"; then
        echo "ERROR: al leer el archivo de configuración" >&2
        echo "Consulta dotsync-conf(1) para más información"
        return 1
    fi
    EXCLUDE+=("${conf_exclude[@]}")
}

is_excluded() {
    if [ "$#" -ne 1 ]; then
        return 1
    fi
    local target=$1
    local pattern
    for pattern in "${EXCLUDE[@]}"; do
        if [[ "$target" == $pattern ]]; then
            return 0
        fi
    done
    return 1
}
