#!/usr/bin/env bash
# Funciones relacionadas con la gestión del repositorio dotsync

edit_file(){ 		# Soporte para editar múltiples archivos depende del editor
	set -x 
	local files=($@)
	local file
	for file in "${files[@]}"; do
		# Si se pasa un enlace simbólico
		if [ -L "$file" ]; then
			file=$(readlink -f "$file")
		fi
		if [[ $(realpath $file) != "$REPO"* ]]; then
			echo "No uses dotsync para editar archivos fuera del repositorio"
			return 1
		fi
	done
	"$EDITOR" "${files[@]}"
	(
		cd "$REPO"
		git add -A > /dev/null
		git commit -m "EDITAR: archivos en el repositorio" -m "Archivos editados: ${files[*]}" > /dev/null
	)
	return 0
}

RECURSION_DEPTH=0

remove_path(){
	if [ "$#" -lt 1 ]; then
		echo "No se ha especificado ningún archivo o directorio"
		return 1
	fi
	# Desvincular enlaces simbólicos
	if [ "$RECURSION_DEPTH" -eq 0 ]; then
        ( cd "$REPO" && stow -D . > /dev/null 2>&1 )
    fi
	((RECURSION_DEPTH++))
	for path in "$@"; do
		if ! [ -e "$path" ]; then 
			echo "ERROR: $path no existe"
			continue
		fi
		local full_path=$(realpath "$path")
		if [[ "$full_path" != "$REPO"* ]]; then
			echo "ERROR: No puedes eliminar elementos fuera del repositorio"
			continue
    	fi
		local real_path="${full_path/$REPO/$HOME}"	# Ruta fuera del repositorio
		if ! mkdir -p "${real_path%/*}"; then
			echo "No se pudo crear directorio para $real_path"
		fi
		local basename="${full_path##*/}"
		if is_excluded "$full_path"; then
			echo "OMITIDO $path"
			continue
		fi
		if [ -f "$full_path" ]; then
			echo "Moviendo $full_path a $real_path"
			if ! mv "$full_path" "$real_path"; then
				echo "ERROR: No se pudo mover el archivo"
				continue;
			fi
			find "$REPO" -mindepth 1 -type d -empty -delete		# Eliminar carpetas vacías
		elif [ -d "$full_path" ]; then
			remove_path "$full_path"/*		# Llama a esta misma función recursivamente
		else 
			echo "ERROR: $path no es un archivo o un directorio"
			continue
		fi
	done
	((RECURSION_DEPTH--))
	if [ "$RECURSION_DEPTH" -eq 0 ]; then	# Si llamada original
		echo "Finalizando sincronización con git y stow"
		(
			cd "$REPO"
			git add -A  > /dev/null
			if ! git diff-index --quiet HEAD --; then	# Evitar comitar sin cambios
                git commit -m "QUITAR: Archivos restaurados al HOME" > /dev/null
            fi
			stow . > /dev/null		# Volver a vincular lo que queda
		)
	fi
	return 0
}

add_path(){
	if [ "$#" -lt 1 ]; then
		echo "No se ha especificado ningún archivo o directorio"
		return 1
	fi
	((RECURSION_DEPTH++))
	for path in "$@"; do
		if [ -L "$path" ]; then
            echo "OMITIDO: $path es un enlace simbólico (posiblemente ya en dotsync)"
            continue
        fi
		if ! [ -e "$path" ]; then 
			echo "ERROR: $path no existe"
			continue
		fi
		local full_path=$(realpath "$path")
		if ! [[ "$full_path" == "$HOME"* ]]; then
			echo "ERROR: No se pudo añadir $full_path porque no está en $HOME"
			continue
		fi
		if [[ "$full_path" == "$REPO"* ]]; then
			echo "ERROR: No puedes añadir el propio repositorio dotsync"
			continue
    	fi
		local repo_path="${full_path/$HOME/$REPO}"	# Ruta en el repositorio dotsync
		local basename="${full_path##*/}"
		if is_excluded "$full_path"; then
		 	echo "OMITIDO $path"
			continue
		fi
		if [ -f "$full_path" ]; then
			if ! mkdir -p "${repo_path%/*}"; then
				echo "ERROR: No se pudo crear directorio ${repo_path%/*}"
				continue;
			fi
			echo "Moviendo $full_path a $repo_path"
			if ! mv "$full_path" "$repo_path"; then
				echo "ERROR: No se pudo mover el archivo"
				continue;
			fi
		elif [ -d "$full_path" ]; then
			add_path "$full_path"/*		# Llama a esta misma función recursivamente
		else 
			echo "ERROR: $path no es un archivo o un directorio"
			continue
		fi
	done
	((RECURSION_DEPTH--))
	if [ "$RECURSION_DEPTH" -eq 0 ]; then	# Si es la primera llamada
		echo "Finalizando sincronización con git y stow"
		(
			cd "$REPO"
			git add -A > /dev/null
			if [ "$#" -eq 1 ]; then
				git commit -m "AÑADIR: $1" -m "Se han añadido $1 al repositorio dotsync" > /dev/null
			else
				git commit -m "AÑADIR: Varios archivos" -m "Se han añadido con éxito varios archivos y/o directorios" > /dev/null
			fi
			stow . > /dev/null
		)
	fi
	return 0
}

init_dotsync(){
	if ! mkdir -p "$REPO"; then
		echo "Error al crear repositorio en $REPO"
		exit 1
	fi
	(
		cd "$REPO"
		if ! git init . --quiet; then
			echo "Error al iniciar repositorio git en $REPO"
			exit 1
		fi
		printf '\.git
				\.gitignore
				\.gitmodules
				^/README*\n' > .stow-local-ignore
		echo "Esta es la carpeta con el contenido del repositorio dotsync" > README
		echo "Se recomienda usar <dotsync edit> para editar los archivos del repositorio" >> README
		echo "Dotsync es un software libre desarollado por Teo Morales (github.com/t-royale) bajo licencia GPLv3" >> README
		echo "Si no has recibido una copia de esta licencia junto al programa visita gnu.org" >> README
		if ! git add . > /dev/null && git commit -m "Commit inicial" > /dev/null; then
			echo "Error al usar git en el repositorio"
			exit 1
		fi
		echo "Repositorio dotsync inicializado con éxito"
	)
}

check_deps(){
    local deps=("$@")
    local all_deps_installed=true
    for program in "${deps[@]}"; do
        if ! type "$program" > /dev/null 2>&1; then
            echo -e "\e[31m$program no está instalado\e[0m"
            get_install_cmd "$program"
            all_deps_installed=false
        fi
    done
    if ! "$all_deps_installed"; then
        return 1
    fi
	return 0
}

get_install_cmd(){
	(	# Ejecutar en subshell para que no se cargue /etc/os-release globalmente
		if [ -f /etc/os-release ]; then
			source /etc/os-release
		else 
			echo -e "\e[31mNo se pudo detectar distribución de Linux\e[0m" >&2
			exit
		fi
		local cmd="$1"
		local DISTRO="$ID"		# ID de distro, se obtiene al cargar /etc/os-release
		local package_manager=""
		case "$DISTRO" in
			debian|ubuntu|linuxmint|elementary|kali|pop|zorin|raspbian|devuan)	package_manager="apt" ;;
			fedora|rhel|centos|rocky|almalinux|ol|scientific) package_manager="dnf" ;;
			arch|manjaro|endeavouros|garuda|artix) package_manager="pacman -S" ;;
			alpine) package_manager="apk add" ;;
			*) 
				echo "No se puede sugerir un método de instalación de dependencias para tu distribución de Linux"
				echo "Para poder continuar, asegúrate de tener las herramientas necesarias instaladas" 
				exit
				;;
		esac
		# Obtener comando de instalación de command-not-found.com
		local install_cmd=$(curl "https://command-not-found.com/$cmd" 2>/dev/null | grep "$package_manager" \
		| sed -e 's/<\/\?code>//g' -e 's/^[[:space:]]*//' | head -n1) # Omitir tags HTML, espacios al principio y líneas innecesarias
		
		if [ -z "$install_cmd" ]; then
			echo -e "\e[31mNo se ha podido entontrar el comando de instalación de $cmd, consulta la documentación de tu distribución ($DISTRO) para instalarlo\e[0m"
		else 
			printf "Instala \e[1m%b\e[0m con el siguiente comando:\n" "$cmd" 
			printf "\t\e[36msudo %b\e[0m\n" "$install_cmd"
		fi
	)
}
