#!/usr/bin/env bash
# Funciones relacionadas con la gestión del repositorio dotsync

init_dotsync(){
	if ! mkdir -p "$REPO"; then
		echo "Error al crear repositorio en $REPO"
		exit 1
	fi
	(
		cd "$REPO"
		if ! git init . --quiet; then
			echo "Error al iniciar repositorio git en $REPO"
			exit 1
		fi
		printf '\.git
				\.gitignore
				\.gitmodules
				^/README*\n' > .stow-local-ignore
		echo "Esta es la carpeta con el contenido del repositorio dotsync" > README
		echo "Se recomienda usar <dotsync edit> para editar los archivos del repositorio" >> README
		echo "Dotsync es un software libre desarollado por Teo Morales (github.com/t-royale) bajo licencia GPLv3" >> README
		echo "Si no has recibido una copia de esta licencia junto al programa visita gnu.org" >> README
		if ! git add . > /dev/null && git commit -m "Commit inicial" > /dev/null; then
			echo "Error al usar git en el repositorio"
			exit 1
		fi
		echo "Repositorio dotsync inicializado con éxito"
	)
}

check_deps(){
    local deps=("$@")
    local all_deps_installed=true
    for program in "${deps[@]}"; do
        if ! type "$program" > /dev/null 2>&1; then
            echo -e "\e[31m$program no está instalado\e[0m"
            get_install_cmd "$program"
            all_deps_installed=false
        fi
    done
    if ! "$all_deps_installed"; then
        return 1
    fi
	return 0
}

get_install_cmd(){
	(	# Ejecutar en subshell para que no se cargue /etc/os-release globalmente
		if [ -f /etc/os-release ]; then
			source /etc/os-release
		else 
			echo -e "\e[31mNo se pudo detectar distribución de Linux\e[0m" >&2
			exit
		fi
		local cmd="$1"
		local DISTRO="$ID"		# ID de distro, se obtiene al cargar /etc/os-release
		local package_manager=""
		case "$DISTRO" in
			debian|ubuntu|linuxmint|elementary|kali|pop|zorin|raspbian|devuan)	package_manager="apt" ;;
			fedora|rhel|centos|rocky|almalinux|ol|scientific) package_manager="dnf" ;;
			arch|manjaro|endeavouros|garuda|artix) package_manager="pacman -S" ;;
			alpine) package_manager="apk add" ;;
			*) 
				echo "No se puede sugerir un método de instalación de dependencias para tu distribución de Linux"
				echo "Para poder continuar, asegúrate de tener las herramientas necesarias instaladas" 
				exit
				;;
		esac
		# Obtener comando de instalación de command-not-found.com
		local install_cmd=$(curl "https://command-not-found.com/$cmd" 2>/dev/null | grep "$package_manager" \
		| sed -e 's/<\/\?code>//g' -e 's/^[[:space:]]*//' | head -n1) # Omitir tags HTML, espacios al principio y líneas innecesarias
		
		if [ -z "$install_cmd" ]; then
			echo -e "\e[31mNo se ha podido entontrar el comando de instalación de $cmd, consulta la documentación de tu distribución ($DISTRO) para instalarlo\e[0m"
		else 
			printf "Instala \e[1m%b\e[0m con el siguiente comando:\n" "$cmd" 
			printf "\t\e[36msudo %b\e[0m\n" "$install_cmd"
		fi
	)
}
