#!/usr/bin/env bash

readonly DEPS=("curl" "git" "stow" "fzf")
readonly CONF="${XDG_CONFIG_HOME:-$HOME/.config}/dotsync/dotsync.conf"
readonly REPO="$HOME/.dotsync"
EXCLUDE=("$REPO" "$REPO/*" "*cache*" "*.log" "*/logs/*" "*/tmp/*")

shopt -s nullglob

main(){
	check_deps "${DEPS[@]}" || exit 1
	load_config || exit 1
	if [ "$#" -lt 1 ]; then
		help
		exit
	fi
	opt="$1"
	shift
	case "$opt" in
		"init") 
			init_dotsync
			;;
		"add")
			if [ "$#" -eq 0 ]; then
				local files=()
				if ui_select_files files; then
					add_path "${files[@]}" || exit 1
				else
					echo "Selección cancelada"
				fi
			else 
				add_path "$files" || exit 1
			fi
			;;
		"list") 
			echo "Listar configuraciones guardadas" 
			;;
		"remove") 
			echo "Eliminar configuración del repositorio dotsync" 
			;;
		"edit") 
			echo "Editar archivo de configuración" 
			;;
		"log") 
			echo "Visualizar cambios realizados en los archivos del repositorio" 
			;;
		"undo") 
			echo "Restaurar cambios realizados en el repositorio" 
			;;
		"export") 
			echo "Exportar repositorio a otro equipo" 
			;;
		"import") 
			echo "Importar repositorio desde un equipo" 
			;;
		"sync") 
			echo "Sincronización con repositorio de git remoto" 
			;;
		"help") 
			help
			;;
	esac
}

help(){
	printf "Uso: <%b> [opción1] [opción2] ...\n" "$0"
	echo -e "\tinit\t- Iniciar repositorio dotsync"
	echo -e "\tadd\t- Añadir archivo o carpeta al repositorio"
	echo -e "\tlist\t- Mostrar elementos del repositorio dotsync"
	echo -e "\tremove\t- Sacar archivo o carpeta del repositorio"
	echo -e "\tedit\t- Editar archivo del repositorio"
	echo -e "\tlog\t- Ver listado de cambios realizados"
	echo -e "\tundo\t- Restaurar cambios en los archivos del repositorio"
	echo -e "\texport\t- Exportar repositorio a otro equipo"
	echo -e "\timport\t- Importar repositorio desde un equipo"
	echo -e "\tsync\t- Opciones de sincronización con repositorio de git remoto"
	echo -e "\thelp\t- Muestra este menú de ayuda"
}

main $@
