#!/usr/bin/env bash

# Funciones relacionadas con la interfaz de usuario

ui_select_commit(){
	(
		cd "$REPO"
		local commit=$(git log --oneline $@ | fzf \
			--header "Selecciona el commit del que ver los cambios (ctrl+C para salir)" \
			--preview 'git show --color=always {1}')
		local hash=$(awk '{print $1}' <<< "$commit")
		echo "$hash"
	)
}

ui_git_diff(){
	(
		local selected=$(ui_select_commit)
		if [ -z "$selected" ]; then
			echo "No se ha seleccionado ningún commit"
			return 0
		fi
		local pager=()
		if command -v batcat > /dev/null; then pager=("batcat" "-l" "diff");
			elif command -v bat > /dev/null ; then pager=("bat" "-l" "Diff");
			else pager=("less" "-R")
		fi
		cd "$REPO"
		local diff=$(git diff "$selected" HEAD)
		if [ -z "$diff" ]; then
			echo "No han habido cambios desde este commit"
			return 0
		fi
		"${pager[@]}" <<< "$diff"
	)
}

ui_set_editor(){
	local editors=("vi" "vim" "nvim" "nano" "emacs")
	for editor in "${editors[@]}"; do
		if command -v "$editor"; then
			local installed_editors="${installed_editors}\n${editor}"
		fi
	done
	if [ -z "$installed_editors" ]; then
		echo "No tienes editores de archivos instalados"
		echo "Se recomienda usar nvim para editar archivos"
		echo "Instala nvim con el siguiente comando"
		get_install_cmd "nvim" 
		return 1
	fi	
	local selected_editor=$(echo -e "$installed_editors" | fzf --header "Selecciona el editor de archivos que prefieras")
	if [ -z "$selected_editor" ]; then
		echo "No se ha seleccionado ningún editor de texto"
		return 1
	fi
	echo "export EDITOR=$selected_editor" >> "$HOME/.bashrc"
	echo "Se ha añadido la variable al sistema, reinicia la terminal o ejecuta \`source ~/.bashrc\` para continuar"
}

ui_select_files(){
	local -n files_arr="$2"		# El output será la variable pasada como segundo argumento
	local -a exclude_path
	for pattern in "${EXCLUDE[@]}"; do
		exclude_path+=("-not" "-path" "$pattern")
	done
	local found_files=$(find "$1" -mindepth 1 -maxdepth 4 "${exclude_path[@]}" -not -type l)
	if [ -z "$found_files" ]; then
		echo "No hay archivos para buscar"
		return 0
	fi
	local selection=$(echo -e "$found_files" | fzf -m --header="Selecciona archivos para añadir (TAB para multi-selección)")
	[ -z "$selection" ] && return 1
	mapfile -t files_arr <<< "$selection"	# Convertir output de fzf a array
}
